task: semantic
image_size: 32
num_classes: 20
epochs: 100
in_channels: 10
max_seq_len: 60
learning_rate: 0.01
use_wandb: false
ignore_index: 19

optimizer: adamw
lr_scheduler: onecycle
output_path: /outputs

loss_fn: cross_entropy
loss_fn_kwargs:
  ignore_index: 19

is_multi_input_model: false
model_name: vistaformer
model_kwargs:
  # Backbone Args
  embed_dims: [32, 64, 128]
  seq_lens: [60, 30, 15]
  patch_sizes:
    - [1, 2, 2]
    - 2
    - 2
  strides:
    - [1, 2, 2]
    - 2
    - 2
  depths:
    - 2
    - 2
    - 2
  num_heads: [2, 4, 8]
  mlp_mult: 4

  # Head Args
  head_conv_dim: 64
  head_upsample_type: trilinear
  head_temporal_agg_type: conv
  head_norm_type: batch
  dropout: 0.175
  drop_path: 0.175
  gate: true
  use_squeeze: false
  activation: gelu

dataset:
  name: pastis
  path: /very/real/path/to/mtlcc
  batch_size: 32
  num_workers: 8

  kwargs:
    use_dates: false
    concat_data: true
    sample_seq: false
    remap_void_label: false
    sats:
      - S2
    train_folds:
      - 3
      - 4
      - 5
    val_folds:
      - 2
    test_folds:
      - 1
